// NiEL — design tokens + plans + themes + types
// v4 — 25 Apr 2026
// LOCKED: RM79/RM399, no free tier, 1 owner + many teachers per centre, class_assignments

// ============ DESIGN TOKENS ============
// Apple-style: SF Pro Display / Inter, tight letter-spacing, pill buttons, off-white bg
export const s = {
  // Apple greys
  bg: '#fbfbfd',
  bgSecondary: '#f5f5f7',
  text: '#1d1d1f',
  textSecondary: '#6e6e73',
  textTertiary: '#9a9a9a',
  border: 'rgba(0,0,0,0.1)',
  borderLight: 'rgba(0,0,0,0.06)',

  // Apple blue (CTA)
  accent: '#0071e3',
  accentDark: '#0058b9',

  // NiEL brand (gradient logo + headline)
  brand: '#185FA5',
  brandDark: '#0C447C',
  brandLight: '#E6F1FB',

  // Status
  success: '#0F6E56',
  successLight: '#E1F5EE',
  warning: '#854F0B',
  warningLight: '#FAEEDA',
  danger: '#A32D2D',
  dangerLight: '#FCEBEB',

  // Fonts (Apple stack)
  fontSans: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro", "Helvetica Neue", "Inter", system-ui, sans-serif',
  fontMono: 'ui-monospace, SF Mono, Menlo, monospace',
} as const

// ============ PER-TUITION THEMES ============
export type ThemeKey = 'blue' | 'green' | 'coral' | 'pink' | 'purple'

export const THEMES: Record<ThemeKey, { accent: string; dark: string; light: string; label: string }> = {
  blue:   { accent: '#185FA5', dark: '#0C447C', light: '#E6F1FB', label: 'Blue' },
  green:  { accent: '#3B6D11', dark: '#27500A', light: '#EAF3DE', label: 'Green' },
  coral:  { accent: '#993C1D', dark: '#712B13', light: '#FAECE7', label: 'Coral' },
  pink:   { accent: '#993556', dark: '#72243E', light: '#FBEAF0', label: 'Pink' },
  purple: { accent: '#3C3489', dark: '#26215C', light: '#EEEDFE', label: 'Purple' },
}

// ============ PLANS · NO FREE TIER ============
export type PlanKey = 'monthly' | 'yearly'

export const PLANS: Record<PlanKey, {
  key: PlanKey
  name: { en: string; bm: string }
  price: number
  durationDays: number
  stripeMode: 'subscription' | 'payment'
  featured?: boolean
}> = {
  monthly: { key: 'monthly', name: { en: 'Monthly', bm: 'Bulanan' }, price: 79, durationDays: 30, stripeMode: 'subscription', featured: true },
  yearly:  { key: 'yearly',  name: { en: 'Yearly',  bm: 'Tahunan'  }, price: 399, durationDays: 365, stripeMode: 'payment' },
}
// RM79 × 12 = RM948 → RM399 saves RM549

// ============ TEACHER ROLES ============
export type TeacherRole = 'owner' | 'teacher'
export type TeacherStatus = 'pending' | 'active' | 'deactivated'

export interface TeacherRecord {
  id: string
  companyId: string
  name: string
  email: string
  role: TeacherRole
  status: TeacherStatus
  createdAt: string
  invitedAt?: string
  inviteTokenHash?: string
  inviteExpiresAt?: string
}

// ============ ROTATING WORDS (LANDING) ============
export const ROTATING_WORDS = ['STUDENT', 'TUTOR', 'PARENT', 'A+'] as const
export const ROTATE_INTERVAL_MS = 2000

// ============ DAILY ENTRY + REPORT TYPES ============
export type EntryTag = 'lacking' | 'ok' | 'improving'

export interface DailyEntry {
  id: string
  studentId: string
  classId: string
  teacherId: string
  sessionDate: string
  topic: string
  score: 1 | 2 | 3 | 4 | 5
  tag: EntryTag
  attended: boolean
  note?: string
}

export interface MonthlyReport {
  id: string
  studentId: string
  classId: string
  month: number
  year: number
  status: 'draft' | 'published'
  avgScore: number
  trendDelta: number
  attendancePct: number
  topicsCovered: { topic: string; avgScore: number; tag: EntryTag; sessions: number }[]
  chartLine: { date: string; score: number }[]
  chartRadar: { area: string; avgScore: number }[]
  doingWell: string
  needsWork: string
  teacherNote?: string
  autoGeneratedAt: string
  publishedAt?: string
}

// ============ FILE CATEGORIES ============
export type FileCategory = 'recordings' | 'worksheets' | 'past_papers' | 'notes'

export const FILE_CATEGORIES: { key: FileCategory; en: string; bm: string }[] = [
  { key: 'recordings',  en: 'Recordings',  bm: 'Rakaman' },
  { key: 'worksheets',  en: 'Worksheets',  bm: 'Lembaran kerja' },
  { key: 'past_papers', en: 'Past papers', bm: 'Kertas lepas' },
  { key: 'notes',       en: 'Notes',       bm: 'Nota' },
]

export const ALLOWED_FILE_TYPES = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'mp3', 'mp4'] as const
export const MAX_FILE_SIZE_MB = 50

// ============ FILTER OPTIONS ============
export const STATES = [
  'Selangor', 'Kuala Lumpur', 'Penang', 'Johor', 'Sabah', 'Sarawak',
  'Perak', 'Kedah', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Terengganu',
  'Kelantan', 'Perlis', 'Putrajaya', 'Labuan',
] as const

export const LEVELS = [
  { key: 'primary',   en: 'Primary',   bm: 'Sekolah Rendah' },
  { key: 'secondary', en: 'Secondary', bm: 'Sekolah Menengah' },
  { key: 'both',      en: 'Both',      bm: 'Kedua-dua' },
] as const

export const MODES = [
  { key: 'physical', en: 'Physical', bm: 'Fizikal' },
  { key: 'online',   en: 'Online',   bm: 'Dalam Talian' },
  { key: 'both',     en: 'Both',     bm: 'Kedua-dua' },
] as const

// ============ RESERVED SLUGS ============
export const RESERVED_SLUGS = [
  'feed', 'centre', 'pricing', 'login', 'signup', 'checkout',
  'dashboard', 'api', 'privacy', 'terms', 'auth', 'admin', 'about',
  'contact', 'support', 'docs', 'blog', 'help', 'app', 'how',
  'teacher', 'parent', 'student',
] as const
